FROM llvm16_debug_x86_nvptx:16.0.6-clang

# Install ASPIS
RUN mkdir /workspace/ASPIS
COPY . /workspace/ASPIS/
WORKDIR /workspace/ASPIS

RUN mkdir build \
    && cmake -B build -DLLVM_DIR=/workspace/llvm-project-16.0.6.src/build/lib/cmake/llvm \
    && cmake --build build


# Export path to add llvm binaries
ENV PATH=/workspace/llvm-project-16.0.6.src/build/bin:$PATH